# Generated by Django 4.2 on 2023-12-24 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('log', models.TextField()),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
